services:
# Clients 1
  consul-client1:
    image: consul-client
    depends_on: 
      - consul-server
    volumes:
      - data_client1:/consul/data
      - /c/tmp:/app
    networks:
      - consul

# Clients 2
  consul-client2:
    image: consul-client
    depends_on: 
      - consul-server
    ports:
      - "80:5000"
    volumes:
      - data_client2:/consul/data
      - /c/tmp:/app
    networks:
      - consul

# Server
  consul-server:
    image: consul-server
    ports:
      - "8500:8500"
    volumes:
      - data_server:/consul/data
    networks:
      - consul

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  consul:
    driver: bridge

volumes:
  data_client1:
  data_client2:
  data_server:
