services:
  consul-client:
    image: consul-client
    depends_on: 
      - consul-server
    volumes:
      - data_client:/consul/data
    networks:
      - consul

  consul-server:
    image: consul-server
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - data_server:/consul/data
    networks:
      - consul

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  consul:
    driver: bridge

volumes:
  data_client:
  data_server:
