FROM ubuntu
	
RUN apt -y update && apt -y upgrade
RUN apt-get install -y consul

# Not necessary but usefull
RUN apt-get install -y iputils-ping
RUN apt-get install -y iproute2

COPY consul-client.d /consul/config/

ENTRYPOINT ["consul"]
CMD ["agent", "-config-dir=/consul/config/"]
