FROM ubuntu

ARG DEBIAN_FRONTEND=noninteractive

RUN apt -y update && apt -y upgrade
RUN apt-get update
RUN apt-get install -y consul

# Not necessary but usefull
RUN apt-get install -y iputils-ping
RUN apt-get install -y iproute2
RUN apt-get install -y curl
RUN apt-get install -y dnsutils

COPY consul-server.d /consul/config/

ENTRYPOINT ["consul"]
CMD ["agent", "-config-dir=/consul/config/"]
